---
- name: check resources
  #callback_plugins = ~/callback_plugins
  hosts: "*db*"
  tasks:
  - name: freedb
    raw: "bash -lc 'db/bin/dbtool -nosession -space -volume -all {{ansible_user_id}} '"
    register: foutput
  #- debug: var=foutput.stdout
    #with_items: foutput.results

  #- name: freedb
  #  shell: db/bin/dbtool -nosession -space -volume -all {{ansible_user_id}}
    #when: not prod
